INSERT INTO accounts (account_Id, residence, age) VALUES (1,"경북",59);
INSERT INTO accounts (account_Id, residence, age) VALUES (2,"세종",73);
INSERT INTO accounts (account_Id, residence, age) VALUES (3,"경기",76);
INSERT INTO accounts (account_Id, residence, age) VALUES (4,"부산",10);
INSERT INTO accounts (account_Id, residence, age) VALUES (5,"경남",65);
INSERT INTO accounts (account_Id, residence, age) VALUES (6,"서울",30);
INSERT INTO accounts (account_Id, residence, age) VALUES (7,"울산",27);
INSERT INTO accounts (account_Id, residence, age) VALUES (8,"대전",76);
INSERT INTO accounts (account_Id, residence, age) VALUES (9,"전북",16);
INSERT INTO accounts (account_Id, residence, age) VALUES (10,"광주",80);
INSERT INTO accounts (account_Id, residence, age) VALUES (11,"세종",53);
INSERT INTO accounts (account_Id, residence, age) VALUES (12,"강원",46);
INSERT INTO accounts (account_Id, residence, age) VALUES (13,"인천",36);
INSERT INTO accounts (account_Id, residence, age) VALUES (14,"충북",48);
INSERT INTO accounts (account_Id, residence, age) VALUES (15,"서울",66);
INSERT INTO accounts (account_Id, residence, age) VALUES (16,"울산",25);
INSERT INTO accounts (account_Id, residence, age) VALUES (17,"서울",57);
INSERT INTO accounts (account_Id, residence, age) VALUES (18,"광주",46);
INSERT INTO accounts (account_Id, residence, age) VALUES (19,"경기",39);
INSERT INTO accounts (account_Id, residence, age) VALUES (20,"서울",31);
INSERT INTO accounts (account_Id, residence, age) VALUES (21,"충북",30);
INSERT INTO accounts (account_Id, residence, age) VALUES (22,"울산",35);
INSERT INTO accounts (account_Id, residence, age) VALUES (23,"경북",20);
INSERT INTO accounts (account_Id, residence, age) VALUES (24,"인천",30);
INSERT INTO accounts (account_Id, residence, age) VALUES (25,"광주",77);
INSERT INTO accounts (account_Id, residence, age) VALUES (26,"경기",39);
INSERT INTO accounts (account_Id, residence, age) VALUES (27,"제주",24);
INSERT INTO accounts (account_Id, residence, age) VALUES (28,"충북",55);
INSERT INTO accounts (account_Id, residence, age) VALUES (29,"강원",15);
INSERT INTO accounts (account_Id, residence, age) VALUES (30,"전남",42);


INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (1,12,106000,"카드","스포츠","충북");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (2,3,1085700,"카드","패션","제주");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (3,27,200900,"송금","도서","대전");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (4,19,808500,"송금","도서","광주");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (5,28,1039800,"카드","스포츠","경기");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (6,22,475000,"카드","도서","대구");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (7,4,1120300,"송금","스포츠","제주");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (8,13,705400,"카드","뷰티","전남");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (9,12,489200,"송금","스포츠","전남");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (10,8,7300,"카드","도서","전북");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (11,3,852500,"카드","식품","충북");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (12,26,463500,"카드","뷰티","경남");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (13,18,533300,"송금","식품","경기");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (14,18,973000,"카드","스포츠","충북");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (15,14,996900,"카드","뷰티","인천");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (16,5,234800,"송금","스포츠","경남");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (17,6,589300,"송금","도서","광주");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (18,5,867000,"송금","식품","대구");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (19,24,1087200,"카드","식품","전북");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (20,27,1175700,"카드","도서","대구");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (21,19,920900,"송금","스포츠","세종");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (22,23,31600,"카드","패션","대구");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (23,25,60200,"송금","식품","서울");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (24,19,675600,"송금","패션","광주");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (25,8,684300,"송금","스포츠","경북");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (26,15,584600,"송금","패션","경북");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (27,15,1155700,"송금","도서","울산");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (28,11,506800,"카드","스포츠","부산");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (29,8,1159900,"송금","도서","충남");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (30,28,722100,"카드","뷰티","제주");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (31,30,166300,"카드","스포츠","제주");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (32,23,617400,"카드","식품","울산");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (33,18,99100,"카드","뷰티","서울");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (34,8,1192500,"카드","뷰티","경북");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (35,18,561500,"카드","스포츠","충북");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (36,5,37900,"카드","스포츠","대구");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (37,5,739400,"송금","식품","제주");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (38,17,814300,"카드","패션","제주");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (39,27,952700,"카드","뷰티","전북");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (40,23,1031700,"카드","식품","경남");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (41,28,586500,"카드","식품","제주");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (42,27,118600,"카드","뷰티","광주");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (43,4,551700,"카드","도서","경기");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (44,18,403200,"송금","식품","서울");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (45,10,267700,"송금","스포츠","부산");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (46,5,929800,"송금","패션","전남");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (47,17,303200,"카드","스포츠","강원");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (48,11,602400,"카드","스포츠","대전");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (49,21,975700,"카드","도서","제주");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (50,29,151700,"카드","패션","대전");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (51,28,519300,"송금","패션","제주");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (52,16,137800,"송금","식품","전북");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (53,24,422100,"카드","스포츠","경기");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (54,11,253200,"카드","식품","인천");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (55,21,682000,"카드","식품","대구");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (56,2,1053500,"송금","뷰티","부산");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (57,29,785900,"카드","뷰티","충북");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (58,22,1197000,"송금","패션","경기");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (59,18,467300,"송금","패션","광주");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (60,6,983300,"카드","스포츠","경북");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (61,27,1148900,"송금","식품","경북");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (62,10,184200,"송금","패션","인천");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (63,11,367200,"카드","도서","부산");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (64,18,718100,"카드","패션","제주");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (65,29,542600,"카드","패션","전북");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (66,14,998400,"카드","스포츠","부산");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (67,21,1116900,"송금","뷰티","제주");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (68,9,1076300,"송금","도서","광주");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (69,24,275600,"카드","도서","울산");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (70,4,608700,"송금","스포츠","인천");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (71,12,644800,"카드","뷰티","세종");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (72,30,370300,"카드","스포츠","대전");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (73,7,1190000,"송금","패션","서울");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (74,2,651400,"카드","도서","경북");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (75,29,1036000,"송금","도서","대구");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (76,12,345400,"카드","뷰티","서울");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (77,19,822600,"카드","스포츠","경기");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (78,9,1095500,"카드","스포츠","제주");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (79,26,584300,"카드","스포츠","강원");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (80,14,437300,"카드","식품","전북");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (81,21,87600,"송금","도서","광주");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (82,28,775300,"카드","도서","경북");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (83,26,1070800,"카드","식품","광주");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (84,27,658200,"송금","도서","대전");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (85,22,501400,"카드","패션","충남");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (86,4,568100,"카드","패션","전북");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (87,15,294000,"카드","스포츠","대구");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (88,21,928400,"송금","도서","울산");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (89,28,1076200,"송금","스포츠","경북");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (90,12,343300,"카드","패션","충북");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (91,27,372100,"카드","도서","부산");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (92,21,451000,"송금","식품","세종");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (93,23,523400,"송금","스포츠","충북");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (94,3,188400,"카드","패션","대전");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (95,16,31700,"송금","식품","경북");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (96,10,1156900,"카드","스포츠","경북");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (97,28,386400,"카드","패션","충남");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (98,2,429700,"송금","식품","경북");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (99,24,1072700,"카드","패션","전북");
INSERT INTO payments (payment_Id, account_Id, amount, method_Type, item_Category, region) VALUES (100,13,1155700,"카드","뷰티","세종");

